import "fake-indexeddb/auto";
import { test } from "node:test";
import assert from "node:assert/strict";
import { devicePacks, downloadPack, queueEdit, pendingEdits, syncEdits } from "../lib/offline/db";
import { KEYS } from "../lib/storage";
const local = new Map<string,string>();
const storage = { getItem:(key:string)=>local.get(key) ?? null, setItem:(key:string,value:string)=>local.set(key,value),removeItem:(key:string)=>local.delete(key) };
const target = new EventTarget();
Object.assign(globalThis,{window:Object.assign(target,{localStorage:storage}),localStorage:storage});
Object.defineProperty(globalThis,"navigator",{value:{onLine:true},configurable:true});
const pack = {id:"test-pack",user_id:"student-a",course_code:"MATH 201",title:"Test",status:"ready",content:{notes:"Server notes",summary:"",cards:[],quiz:[],lessons:[]},updated_at:"2026-10-01T00:00:00Z"};
local.set(KEYS.ACCOUNT,JSON.stringify({id:"student-a"}));
test("unsynced notes survive remote refresh; newer edits survive in-flight sync; other accounts cannot read them",async()=>{
 await downloadPack(pack);
 await queueEdit(pack,"notes","Train notes");
 globalThis.fetch=async()=>new Response('{}',{status:503});
 await syncEdits();
 await downloadPack(pack);
 assert.equal((await devicePacks())[0].content.notes,"Train notes");
 assert.equal(await pendingEdits(),1);
 globalThis.fetch=async()=>{ await queueEdit(pack,"notes","Newer train notes"); return new Response('{}'); };
 await syncEdits();
 assert.equal(await pendingEdits(),1);
 assert.equal((await devicePacks())[0].content.notes,"Newer train notes");
 globalThis.fetch=async()=>new Response('{}');
 await syncEdits();
 assert.equal(await pendingEdits(),0);
 local.set(KEYS.ACCOUNT,JSON.stringify({id:"student-b"}));
 assert.equal((await devicePacks()).length,0);
 await assert.rejects(downloadPack(pack),/account/);
});
