export const ALGEBRA_CASES = [
  { question: "Plot the points (2,3) and (-1,-2).", expr: "x", x: 2, y: 2 },
  { question: "Graph y=2x+1 and find its slope.", expr: "2*x+1", x: 2, y: 5 },
  {
    question: "Graph y=-3x+4 and find the intercept.",
    expr: "-3*x+4",
    x: 0,
    y: 4,
  },
  {
    question: "Plot y=x squared and identify the vertex.",
    expr: "x^2",
    x: 2,
    y: 4,
  },
  { question: "Plot y=(x-2) squared minus 1.", expr: "(x-2)^2-1", x: 2, y: -1 },
  { question: "Graph y=-x squared plus 4.", expr: "-x^2+4", x: 2, y: 0 },
  { question: "Find the x-intercept of y=3x-6.", expr: "3*x-6", x: 2, y: 0 },
  { question: "Explain a horizontal line y=3.", expr: "3", x: -2, y: 3 },
  { question: "Compare y=x and y=-x.", expr: "-x", x: 3, y: -3 },
  {
    question: "Graph y=abs(x) and explain the corner.",
    expr: "abs(x)",
    x: -2,
    y: 2,
  },
  { question: "Graph y=sqrt(x) and its domain.", expr: "sqrt(x)", x: 4, y: 2 },
  {
    question: "Graph y=1/x without joining the asymptote.",
    expr: "1/x",
    x: 2,
    y: 0.5,
  },
  {
    question: "Graph y=1/(x-1) and identify x=1.",
    expr: "1/(x-1)",
    x: 2,
    y: 1,
  },
  {
    question: "Solve the intersection y=2x+1 and y=-x+4.",
    expr: "2*x+1",
    x: 1,
    y: 3,
  },
  {
    question: "Graph the line through (0,-2) and (2,2).",
    expr: "2*x-2",
    x: 2,
    y: 2,
  },
  {
    question: "Plot y=0.5x+2 and compare its steepness.",
    expr: "0.5*x+2",
    x: 4,
    y: 4,
  },
  { question: "Graph y=x cubed and its intercept.", expr: "x^3", x: -2, y: -8 },
  {
    question: "Graph y=(x+1) squared and its vertex.",
    expr: "(x+1)^2",
    x: -1,
    y: 0,
  },
  {
    question: "Graph y=2x squared and compare to y=x squared.",
    expr: "2*x^2",
    x: 2,
    y: 8,
  },
  {
    question: "Graph y=4-x squared and find both roots.",
    expr: "4-x^2",
    x: -2,
    y: 0,
  },
] as const;
